name: Docs CI action
description: 'Lint docs, build and test mdBook'
runs:
  using: "composite"
  steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: '0.4.43'

    - name: Test docs
      shell: bash
      run: mdbook test

    - name: Build docs
      shell: bash
      run: mdbook build

    - name: Check markdown linting
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: |
          README.md
          docs/*.md
