name: Release xgov-beta-sc

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate xgov-beta-sc
    uses: ./.github/workflows/xgov-beta-sc-ci.yml
    secrets: inherit
  deploy-fnet:
    runs-on: "ubuntu-latest"
    needs: validate
    environment: contract-fnet
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Bootstrap dependencies
        run: algokit project bootstrap all

      - name: Configure git
        shell: bash
        run: |
          # set git user and email as test invoke git
          git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Deploy to fnet
        run: algokit project deploy fnet
        env:
          # This is the account that becomes the creator of the contract
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          # The dispenser account is used to ensure the deployer account is funded
          DISPENSER_MNEMONIC: ${{ secrets.DISPENSER_MNEMONIC }}
          # Pinata API JWT to publish deployed App Spec on IPFS
          ALGOKIT_PINATA_JWT: ${{ secrets.ALGOKIT_PINATA_JWT }}
          # Registry configuration
          XGOV_CFG_XGOV_FEE: ${{ vars.XGOV_FEE }}
          XGOV_CFG_PROPOSER_FEE: ${{ vars.PROPOSER_FEE }}
          XGOV_CFG_PROPOSAL_FEE: ${{ vars.PROPOSAL_FEE }}
          XGOV_CFG_PROPOSAL_PUBLISHING_BPS: ${{ vars.PROPOSAL_PUBLISHING_BPS }}
          XGOV_CFG_PROPOSAL_COMMITMENT_BPS: ${{ vars.PROPOSAL_COMMITMENT_BPS }}
          XGOV_CFG_MIN_REQUESTED_AMOUNT: ${{ vars.MIN_REQUESTED_AMOUNT }}
          XGOV_CFG_MAX_REQUESTED_AMOUNT: ${{ vars.MAX_REQUESTED_AMOUNT }}
          XGOV_CFG_DISCUSSION_DURATION: ${{ vars.DISCUSSION_DURATION }}
          XGOV_CFG_VOTING_DURATION: ${{ vars.VOTING_DURATION }}
          XGOV_CFG_COOL_DOWN_DURATION: ${{ vars.COOL_DOWN_DURATION }}
          XGOV_CFG_QUORUM: ${{ vars.QUORUM }}
          XGOV_CFG_WEIGHTED_QUORUM: ${{ vars.WEIGHTED_QUORUM }}
