name: Release xgov-beta-sc

on:
  workflow_dispatch:
    inputs:
      fresh-deploy:
        description: "Deploy fresh contract"
        required: false
        default: "false"
        type: boolean
      xgov-reg-configure:
        description: "Configure xgov-reg contract"
        required: false
        default: "false"
        type: boolean
  workflow_call:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate xgov-beta-sc
    uses: ./.github/workflows/xgov-beta-sc-ci.yml
    secrets: inherit
  deploy-testnet:
    runs-on: "ubuntu-latest"
    needs: validate
    environment: contract-testnet
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Bootstrap dependencies
        run: algokit project bootstrap all

      - name: Configure git
        shell: bash
        run: |
          # set git user and email as test invoke git
          git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Deploy to testnet
        run: algokit project deploy testnet
        env:
          # This is the account that becomes the creator of the contract
          DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
          # The dispenser account is used to ensure the deployer account is funded
          DISPENSER_MNEMONIC: ${{ secrets.DISPENSER_MNEMONIC }}
          # Pinata API JWT to publish deployed App Spec on IPFS
          ALGOKIT_PINATA_JWT: ${{ secrets.ALGOKIT_PINATA_JWT }}
          # Should the contract be deployed fresh?
          XGOV_REG_FRESH_DEPLOY: ${{ github.event.inputs.fresh-deploy || 'false' }}
          # Should the contract be configured?
          XGOV_REG_CONFIGURE: ${{ github.event.inputs.xgov-reg-configure || 'false' }}
          # Registry configuration
          XGOV_CFG_XGOV_FEE: ${{ vars.XGOV_FEE || '1_000_000'  }} # defaults: 1 ALGO in microALGO
          XGOV_CFG_PROPOSER_FEE: ${{ vars.PROPOSER_FEE || '1_000_000'  }} # defaults: 1 ALGO in microALGO
          XGOV_CFG_OPEN_PROPOSAL_FEE: ${{ vars.OPEN_PROPOSAL_FEE || '100_000_000'  }} # defaults: 100 ALGO in microALGO
          XGOV_CFG_DAEMON_OPS_FUNDING_BPS: ${{ vars.DAEMON_OPS_FUNDING_BPS || '500'  }} # defaults: 5% in bps
          XGOV_CFG_PROPOSAL_COMMITMENT_BPS: ${{ vars.PROPOSAL_COMMITMENT_BPS || '300'  }} # defaults: 3% in bps
          XGOV_CFG_MIN_REQUESTED_AMOUNT: ${{ vars.MIN_REQUESTED_AMOUNT || '1_000_000'  }} # defaults: 1 ALGO in microALGO
          XGOV_CFG_MAX_REQUESTED_AMOUNT: ${{ vars.MAX_REQUESTED_AMOUNT || '10_000_000,20_000_000,30_000_000'  }} # defaults: 10 (S), 20 (M), 30 (L) ALGO in microALGO
          XGOV_CFG_DISCUSSION_DURATION: ${{ vars.DISCUSSION_DURATION || '60,60,60,60'  }} # defaults: 1 (S), 1 (M), 1 (L), 1 (XL) minute in seconds
          XGOV_CFG_VOTING_DURATION: ${{ vars.VOTING_DURATION || '3_600,3_600,3_600,3_600'  }} # defaults: 1 (S), 1 (M), 1 (L), 1 (XL) hours in seconds
          XGOV_CFG_QUORUM: ${{ vars.QUORUM || '500,1_000,2_000'  }} # defaults: 5 (S), 10 (M), 20 (L) % in bps
          XGOV_CFG_WEIGHTED_QUORUM: ${{ vars.WEIGHTED_QUORUM || '500,1_000,2_000'  }} # defaults: 5 (S), 10 (M), 20 (L) % in bps
