name: Validate xgov-beta-sc

on:
  workflow_call:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'  # Run once a week at midnight on Sunday	

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Start LocalNet
        run: algokit localnet start

      - name: Bootstrap dependencies
        run: algokit project bootstrap all --project-name 'xgov-beta-sc'

      - name: Configure git
        shell: bash
        run: |
          # set git user and email as test invoke git
          git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Audit python dependencies
        run: algokit project run audit --project-name 'xgov-beta-sc'

      - name: Lint and format python dependencies
        run: algokit project run lint --project-name 'xgov-beta-sc'

      - name: Run tests
        shell: bash
        run: |
          set -o pipefail
          algokit project run test --project-name 'xgov-beta-sc'

      - name: Build smart contracts
        run: algokit project run build --project-name 'xgov-beta-sc'

      - name: Scan TEAL files for issues
        run: algokit project run audit-teal --project-name 'xgov-beta-sc'

      - name: Check output stability of the smart contracts
        run: algokit project run ci-teal-diff --project-name 'xgov-beta-sc'

      - name: Run deployer against LocalNet
        run: algokit project deploy localnet --project-name 'xgov-beta-sc'
